force-app/main/default/objects/Order_Event__e/Order_Event__e.object-meta.xml
<CustomObject>
    <description>Information about a customer</description>
    <label>Order Event</label>
    <pluralLabel>Order Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order_Event__e/fields/Has_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Has_Shipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Shipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Event__e/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuickTester.cls
@isTest
public class QuickTester {
    @testSetup
    static void dataSetup(){
        Account acc = new Account();
        acc.Name = 'bar';
        acc.BillingCity = '525 S. Lexington Ave';
        acc.BillingState = 'NC';
        acc.BillingPostalCode = '27215';
        acc.BillingCountry = 'USA';
        insert acc;
        
        
        Tower__c tower = new Tower__C();
        tower.Name = 'foo';
        tower.State__c = acc.id;
        insert tower;
    }
    
    @isTest
    static void testTowerAura(){
    	TowerMapControllerClass.getAllTowers();
    }
    
    
    @isTest
    static void testEvents(){
        List<Order_Event__e> ordList = new List<Order_Event__e>();
        Order_Event__e ord = new Order_Event__e();
        ord.Has_Shipped__c = true;
        ord.Order_Number__c  = '10';  
        ordList.add(ord);
        Test.startTest();
        List<Database.SaveResult> results = EventBus.publish(ordList);
        Test.stopTest();

        
    }
}